variables:
  MAVEN_IMAGE: "maven:3.5.2-jdk-8"
  MAVEN_IMAGE_JDK_8: "maven:3.5.2-jdk-8"
  LOCAL_REPO: "127.0.0.1:5000"

  DOCKER_REPO: "gitlab.ow2.org:4567"
  DOCKER_DIND_IMAGE: "docker:19.03.1"
  DOCKER_DIND_SERVICE: "$DOCKER_DIND_IMAGE-dind"
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: "/certs"

  DOCKER_CLI: "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $CI_PROJECT_DIR/maven_repo:/root/.m2 -w /usr/src/mymaven -v $CI_PROJECT_DIR:/usr/src/mymaven $MAVEN_IMAGE"
  UF_CREATOR_CLI: "mvn --batch-mode -N -Dmaven.test.skip=true -f Uf-Creator/pom.xml"

cache:
  paths:
    - maven_repo/
    
before_script:
  - echo $HOME
  - mkdir -p /root/.m2
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                            https://maven.apache.org/xsd/settings-1.0.0.xsd">
                <localRepository>'$CI_PROJECT_DIR'/maven_repo</localRepository>
          </settings>' > /root/.m2/settings.xml
  - echo "MAVEN_OPTS=$MAVEN_OPTS" > $CI_PROJECT_DIR/.env.list
    
stages:          
  - build-angular-ui
  - deploy-angular-ui
  - build-UfCreator
  - deploy-UfCreator

build-angular-ui:
  stage: build-angular-ui
  image: trion/ng-cli
  artifacts:
    paths:
      - dist/UfCreatorUI
  before_script:
    - cd UfCreatorUI
    - npm install -g --save-dev @angular/cli@latest
    - npm install --save-dev  --unsafe-perm node-sass@6.0.1
  script: 
    - ng build --configuration production 
    - cd dist
    - ls

deploy-angular-ui:
  stage: deploy-angular-ui
  only:
    - main
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  dependencies:
    - build-angular-ui
  script:
    - docker pull nginx
    - cd UfCreatorUI
    - docker login gitlab.ow2.org:4567 -u $K8S_SECRET_DOCKER_USER -p $K8S_SECRET_DOCKER_PASSWORD
    - docker build -t gitlab.ow2.org:4567/melodic/uf-creator/front:$CI_COMMIT_BRANCH .
    - docker push gitlab.ow2.org:4567/melodic/uf-creator/front:$CI_COMMIT_BRANCH

build-UfCreator:
  stage: build-UfCreator
  image: $MAVEN_IMAGE_JDK_8
  script:
    - ls
    - $UF_CREATOR_CLI clean install
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/Uf-Creator/target
      - $CI_PROJECT_DIR/Uf-Creator/


deploy-UfCreator:
  stage: deploy-UfCreator
  image: $DOCKER_DIND_IMAGE
  only:
    - main
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-UfCreator
  script:
    - cd Uf-Creator/src/main/docker
    - $DOCKER_CLI $UF_CREATOR_CLI deploy
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker build -t gitlab.ow2.org:4567/melodic/uf-creator/backend:$CI_COMMIT_BRANCH .
    - docker push gitlab.ow2.org:4567/melodic/uf-creator/backend:$CI_COMMIT_BRANCH






